---
name: Build Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: [windows-latest]
    timeout-minutes: 15
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: CMake Setup
        shell: bash
        working-directory: build
        run: |
          export UseMultiToolTask=true
          cmake .. -DCMAKE_UNITY_BUILD=ON -DSRCML_BUILD_PCH=ON

      - name: Build
        shell: bash
        working-directory: build
        run: |
          export UseMultiToolTask=true
          cmake --build . --config Release

      - name: Package
        id: package
        shell: bash
        continue-on-error: true
        working-directory: build
        run: |
          cpack -G WIX -V
      - uses: actions/upload-artifact@v2
        if: steps.package.outcome != 'success'
        with:
          name: WIXLog
          path: build\dist\_CPack_Packages\win64\WIX\wix.log
      - uses: actions/upload-artifact@v2
        if: steps.package.outcome == 'success'
        with:
          name: WindowsInstaller
          path: build\dist\srcML-Win.msi
