---
name: Test Single Use Fedora

on: workflow_dispatch

jobs:
  package:
    runs-on: ubuntu-latest
    continue-on-error: true
    # container: 
    #   image: ubuntu:21.10
    #   options: --platform linux/arm64/v8

    timeout-minutes: 10
    steps:

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Start arm64 Docker
        shell: bash
        run: |
          /usr/bin/docker ps --all --quiet --no-trunc --filter "label=8a33c1"
          /usr/bin/docker network prune --force --filter "label=8a33c1"
          /usr/bin/docker network create --label 8a33c1 --name srcmlnet
          /usr/bin/docker pull ubuntu:21.10
          /usr/bin/docker create --platform linux/arm64/v8 --name arm --label 8a33c1 --workdir /__w/srcML/srcML --network srcmlnet  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.278.0/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" ubuntu:21.10 "-f" "/dev/null"
          /usr/bin/docker start arm
          /usr/bin/docker ps --all 
          /usr/bin/docker inspect arm

      - shell: bash
        run: uname -m

      - shell: bash
        run: docker exec arm uname -m
