---
name: Test Home

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Experiment
        shell: bash
        run: |
          echo $HOMESTUFF
