---
name: Test Single Use Fedora

on: workflow_dispatch

jobs:
  package:
    runs-on: ubuntu-latest
    continue-on-error: true
    container: 
      image: ubuntu:21.10
      options: --platform linux/arm64/v8

    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: OS Version
        shell: bash
        run: |
          cat /etc/os-release
          uname -m
