---
name: Test Single Use Fedora

on: workflow_dispatch

jobs:
  package:
    runs-on: ubuntu-18.04
    continue-on-error: true
    # container: 
    #   image: ubuntu:21.10
    #   options: --platform linux/arm64/v8

    timeout-minutes: 10
    steps:

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: OS Version
        shell: bash
        run: |
          /usr/bin/docker pull ubuntu:21.10
          /usr/bin/docker create --platform linux/arm64/v8 --name arm --entrypoint "tail" ubuntu:21.10 -f /dev/null
          /usr/bin/docker start arm
          /usr/bin/docker ps --all 
          /usr/bin/docker inspect all

      - shell: bash
        run: uname -m
