---
name: Test Single Use Fedora

on: workflow_dispatch

jobs:
  package:
    runs-on: ubuntu-latest
    continue-on-error: true
    # container: 
    #   image: ubuntu:21.10
    #   options: --platform linux/arm64/v8

    timeout-minutes: 10
    steps:

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: OS Version
        shell: bash
        run: |
          /usr/bin/docker run --workdir /__w/srcML/srcML --platform linux/arm64/v8 -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/opt/hostedtoolcache":"/__t" --entrypoint "tail" ubuntu:21.10 "-f" "/dev/null"
          /usr/bin/docker ps -a

      - name: Checkout Repository
        uses: actions/checkout@v2
