---
name: Test Fedora

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        tag: [rawhide, 35, latest, 34, 33, 32]
    runs-on: ubuntu-latest
    container: srcml/fedora:${{ matrix.tag }}
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: OS Version
        shell: bash
        run: |
          cat /etc/os-release

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: CMake Setup
        shell: bash
        working-directory: build
        run: |
          cmake .. -G Ninja

      - name: Build
        shell: bash
        working-directory: build
        run: |
          ninja

      - name: Package
        shell: bash
        working-directory: build
        run: |
          cpack -G RPM

      - uses: actions/upload-artifact@v2
        with:
          name: FedoraDist
          path: build/dist/*.rpm
