---
name: Test Fedora

on: workflow_dispatch

jobs:
  package:
    strategy:
      matrix:
        distribution: [rawhide, 35, latest, 34, 33, 32]
    runs-on: ubuntu-latest
    container: srcml/fedora:${{ matrix.distribution }}
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
