---
name: Test Fedora

on: workflow_dispatch

jobs:
  package:
    strategy:
      matrix:
        distribution: [fedora:rawhide, fedora:35, fedora:latest, fedora:34, fedora:33, fedora:32]
    runs-on: ubuntu-latest
    container: srcml/${{ matrix.distribution }}
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
